### ISSUE TITLE
error: "ffmpegArgs" must not be a sparse array

### ISSUE THREAD

**Issue by christianvogt** [fabric8io/fabric8-test#1111]
Attempting to run the ee_tests locally on a mac and I get the following error:

```
16:51:53] E/configParser - Error code: 105
[16:51:53] E/configParser - Error message: failed loading configuration file target/ts-output/protractor.config.js
[16:51:53] E/configParser - ValidationError: child "ffmpegArgs" fails because ["ffmpegArgs" must not be a sparse array]
    at Object.exports.process (/Users/cvogt/dev/ws/fabric8-ui/fabric8-test/ee_tests/node_modules/joi/lib/errors.js:152:19)
    at internals.Object.internals.Any._validateWithOptions (/Users/cvogt/dev/ws/fabric8-ui/fabric8-test/ee_tests/node_modules/joi/lib/any.js:633:27)
    at module.exports.internals.Any.root.validate (/Users/cvogt/dev/ws/fabric8-ui/fabric8-test/ee_tests/node_modules/joi/lib/index.js:104:23)
    at new VideoReporter (/Users/cvogt/dev/ws/fabric8-ui/fabric8-test/ee_tests/node_modules/protractor-video-reporter/lib/VideoReporter.js:43:20)
    at Object.<anonymous> (/Users/cvogt/dev/ws/fabric8-ui/fabric8-test/ee_tests/target/ts-output/protractor.config.js:24:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

A simple workaround I found is the not create a new `VideoReporter` unless `useVideoReporter` is set to `true` in `protractor.config.ts`.

**Comment by ppitonak** [comment]
@christianvogt please reopen in the case that fix didn't resolve the issue... we don't have Mac.
