### ISSUE TITLE
Improve error handling for e2e tests

### ISSUE THREAD

**Issue by ljelinkova** [fabric8io/fabric8-test#1167]
When something goes wrong in the tests, they sometimes log 

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```
and continue and fail on random place later. It makes it hard to track where the error originated. 

I believe that our error handling through try/catch blocks is not good, though I am not entirely sure why. 
I created 2 examples when it works and when it does not

This works as expected
```
it('local', async () => {
        logger.info('Before call');
        await first();
        logger.info('After call');
    });

    async function first(): Promise<void> {
        try {
            await second();
        } catch (e) {
            logger.info('Error ' + e);
        }
    }

    async function second(): Promise<void> {
        await Promise.reject();
    }
```

However, this throws UnhandledPromiseRejectionWarning (the only difference is the await in the second() method)

```
it('local', async () => {
        logger.info('Before call');
        await first();
        logger.info('After call');
    });

    async function first(): Promise<void> {
        try {
            await second();
        } catch (e) {
            logger.info('Error ' + e);
        }
    }

    async function second(): Promise<void> {
        Promise.reject();
    }
```

**Comment by ljelinkova** [comment]
Example of failed che test
```
Create and open workspace
[09:09:27.323]        Button('Create Codespace...'): waiting for "clickable"   | timeout: '600000'
[09:09:27.325]        Button('Open Workspace...'): waiting for "clickable"   | timeout: '600000'
[09:09:27.573]        Button('Create Codespace...'): waiting for "clickable"   - OK
[09:09:27.853]        Button('Create Codespace...'): Clicked
[09:09:29.329]     Waiting for the specified number or windows to be present: 2
(node:78) UnhandledPromiseRejectionWarning: TimeoutError: Wait timed out after 60011ms
    at /opt/fabric8-test/node_modules/selenium-webdriver/lib/promise.js:2201:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:78) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:78) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ljelinkova** [comment]
It seems that there are more examples when missing await caused unexpected behavior so I am closing this issue and we will resolve those issue as they occur.

**Comment by ppitonak** [comment]
For the record, there is a TSLint rule watching for floating promises https://palantir.github.io/tslint/rules/no-floating-promises/ but when I activate it, it requires await before each `expect`. 

I suggest to leave it inactive and just check it from time to time.
