### ISSUE TITLE
stack traces not including the messages?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-test#138]
i've noticed when timeouts fail we lose the useful message in the code. See the sample output of the test below. The code that actually failed is this line:
```js
    browser.wait(until.presenceOf(OpenShiftIoDashboardPage.jenkinsStatusPoweredOn), constants.RESET_TENANT_WAIT), "Timeout waiting for Jenkins to start after tenant update - see: https://github.com/openshiftio/openshift.io/issues/595";
```
yet that nice message is lost so the stack trace is not that meaningful (unless you then go through the stack lines to find the code that caused the error).

Its really nice getting tests to give as meaningful errors as possible when things go wrong to minimise time wasted trying to grok the failure. I wonder if we can try get the message included in the failure message?

```
Failed: Wait timed out after 300005ms
TimeoutError: Wait timed out after 300005ms
    at /workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2107:17
    at ManagedPromise.invokeCallback_ (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: <anonymous wait>
    at scheduleWait (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2094:20)
    at ControlFlow.wait (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2408:12)
    at thenableWebDriverProxy.wait (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/webdriver.js:943:29)
    at run (/workspace/java/fabric8-test/ee_tests/node_modules/protractor/lib/browser.ts:66:27)
    at ProtractorBrowser.to.(anonymous function) [as wait] (/workspace/java/fabric8-test/ee_tests/node_modules/protractor/lib/browser.ts:74:12)
    at Object.loginCleanUpdate (/workspace/java/fabric8-test/ee_tests/src/tests/work-item/work-item-list/testSupport.js:178:13)
    at runTheTest (/workspace/java/fabric8-test/ee_tests/src/tests/work-item/work-item-list/EE/openshift-io-burr-quickstart.spec.js:132:44)
    at UserContext.<anonymous> (/workspace/java/fabric8-test/ee_tests/src/tests/work-item/work-item-list/EE/openshift-io-burr-quickstart.spec.js:90:7)
    at /workspace/java/fabric8-test/ee_tests/node_modules/jasminewd2/index.js:112:25
    at new ManagedPromise (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:1067:7)
    at ControlFlow.promise (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2396:12)
    at schedulerExecute (/workspace/java/fabric8-test/ee_tests/node_modules/jasminewd2/index.js:95:18)
    at TaskQueue.execute_ (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2860:25)
    at /workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: Run it("should perform Quickstart test - CREATE project - Run Pipeline - Vert.x - Basic") in control flow
    at UserContext.<anonymous> (/workspace/java/fabric8-test/ee_tests/node_modules/jasminewd2/index.js:94:19)
    at attempt (/workspace/java/fabric8-test/ee_tests/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4297:26)
    at QueueRunner.run (/workspace/java/fabric8-test/ee_tests/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4217:20)
    at runNext (/workspace/java/fabric8-test/ee_tests/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4257:20)
    at /workspace/java/fabric8-test/ee_tests/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4264:13
    at /workspace/java/fabric8-test/ee_tests/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4172:9
    at /workspace/java/fabric8-test/ee_tests/node_modules/jasminewd2/index.js:64:48
    at ControlFlow.emit (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/events.js:62:21)
    at ControlFlow.shutdown_ (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2565:10)
    at shutdownTask_.MicroTask (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2490:53)
    at MicroTask.asyncRun (/workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:2619:9)
    at /workspace/java/fabric8-test/ee_tests/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by jstrachan** [comment]
DOH! the source was wrong! note the badly placed `)` :)
