### ISSUE TITLE
How would I find the associated test?

### ISSUE THREAD

**Issue by luebken** [fabric8io/fabric8-test#21]
When I run the license test I get a failure. But unfortunately I can't see the test-case. I need to jump to line 55 to see that it's Testcase: Test-1704E469-04. Can we report the test-case when a failure happens?

```
jasmine-node api/1704E469-license.spec.js --config targetURL https://recommender.api.openshift.io/api/v1/
.....F

Failures:

  1) Frisby Test: Connecting to REST API - endpoint :: https://recommender.api.openshift.io/api/v1/maven/org.springframework:spring-core/4.3.3.RELEASE
	[ GET https://recommender.api.openshift.io/api/v1/component-analyses/maven/org.springframework:spring-core/4.3.3.RELEASE ]
   Message:
     Expected [ 'ASL 2.0', 'LBNL BSD' ] to contain 'Apache 2.0'.
   Stacktrace:
     Error: Expected [ 'ASL 2.0', 'LBNL BSD' ] to contain 'Apache 2.0'.
    at Frisby.<anonymous> (/Users/mdl/workspace/git-hub-lib/redhat/fabric8-test/analytics_EE_tests/api/1704E469-license.spec.js:55:58)
    at Frisby.<anonymous> (/Users/mdl/workspace/git-hub-lib/redhat/fabric8-test/analytics_EE_tests/node_modules/frisby/lib/frisby.js:951:8)
    at jasmine.Spec.<anonymous> (/Users/mdl/workspace/git-hub-lib/redhat/fabric8-test/analytics_EE_tests/node_modules/frisby/lib/frisby.js:1112:18)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)

Finished in 2.161 seconds
6 tests, 8 assertions, 1 failure, 0 skipped

```

**Comment by naina-verma** [comment]
@luebken can you plz pull later origin master and try !

**Comment by luebken** [comment]
(Note we chatted about it and it didn't work)

**Comment by naina-verma** [comment]
this needs to be fixed !

**Comment by ljelinkova** [comment]
Outdated.
